name: restaurant_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.3.0
  lottie: ^3.3.1
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/loading.json
    - assets/lottie/empty.json
    - assets/lottie/search.json
    - assets/lottie/error.json
    - assets/images/food.png
    - assets/images/drink.png
    - assets/images/user.png


  fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee/ABeeZee-Regular.ttf
          weight: 400
    - family: AnekOdia
      fonts:
        - asset: assets/fonts/AnekOdia/AnekOdia-Bold.ttf
          weight: 700
        - asset: assets/fonts/AnekOdia/AnekOdia-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/AnekOdia/AnekOdia-Medium.ttf
          weight: 500
        - asset: assets/fonts/AnekOdia/AnekOdia-Regular.ttf
          weight: 400
        - asset: assets/fonts/AnekOdia/AnekOdia-Light.ttf
          weight: 300
        - asset: assets/fonts/AnekOdia/AnekOdia-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/AnekOdia/AnekOdia-Thin.ttf
          weight: 100
